name = "Lean-ZFC"
version = "0.1.0"
defaultTargets = ["lean-zfc"]

[[lean_lib]]
name = "LeanZFC"
srcDir = "."
globs = ["LeanZFC", "Propositional.*", "First_Order.*"]

[[lean_exe]]
name = "lean-zfc"
root = "Main"
